package com.dwbuilder.app

import com.dwbuilder.app.data.arr
import com.dwbuilder.app.data.int
import com.dwbuilder.app.data.obj
import com.dwbuilder.app.data.parseJson
import com.dwbuilder.app.domain.Points
import com.dwbuilder.app.domain.ShrineRules
import com.dwbuilder.app.domain.model.Attributes
import com.dwbuilder.app.domain.model.Build
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Cross-validates the Kotlin shrine engine against golden fixtures generated by
 * an independent Python transcription of the site's JavaScript (`$b`, `Pn`,
 * `qb`, derived power/points). See `scripts/golden_shrine.py` and
 * `src/test/resources/golden/shrine.json` for the derivation.
 */
class ShrineRulesGoldenTest {

    private fun cases(): List<JsonObject> {
        val stream = ShrineRulesGoldenTest::class.java.classLoader
            .getResourceAsStream("golden/shrine.json")
            ?: error("missing test resource golden/shrine.json")
        val root = parseJson(stream.bufferedReader().use { it.readText() }) as JsonObject
        return root.arr("cases").mapNotNull { it as? JsonObject }
    }

    private fun jsonObject(o: JsonObject): Map<String, Int> =
        o.mapNotNull { (k, v) -> (v as? JsonPrimitive)?.contentOrNull?.toIntOrNull()?.let { k to it } }.toMap()

    private fun attrsOf(o: JsonObject?): Attributes = Attributes(
        base = jsonObject(o?.obj("base") ?: JsonObject(emptyMap())),
        weapon = jsonObject(o?.obj("weapon") ?: JsonObject(emptyMap())),
        attunement = jsonObject(o?.obj("attunement") ?: JsonObject(emptyMap())),
    )

    @Test
    fun redistributionMatchesSiteAlgorithmOverAllGoldenSteps() {
        for (c in cases()) {
            val name = c["name"]?.let { (it as? JsonPrimitive)?.content } ?: "?"
            val input = attrsOf(c.obj("input"))
            val race = jsonObject(c.obj("raceBonuses") ?: JsonObject(emptyMap()))
            val expected = attrsOf(c.obj("redistributed"))
            assertEquals(expected, ShrineRules.redistribute(input, race), "redistribute($name)")
        }
    }

    @Test
    fun applyOrderProducesGoldenPostStateAndSparePoints() {
        for (c in cases()) {
            val name = c["name"]?.let { (it as? JsonPrimitive)?.content } ?: "?"
            val input = attrsOf(c.obj("input"))
            val race = jsonObject(c.obj("raceBonuses") ?: JsonObject(emptyMap()))
            val mastery = jsonObject(c.obj("mastery") ?: JsonObject(emptyMap()))
            val build = Build(attributes = input, preMastery = mastery)

            val result = ShrineRules.applyOrder(build, race)
            val order = c.obj("order") ?: JsonObject(emptyMap())

            assertEquals(attrsOf(order.obj("post")), result.build.attributes, "applyOrder.post($name)")
            assertEquals(order.int("sparePoints") ?: 0, result.sparePoints, "applyOrder.spare($name)")
            assertEquals("post", result.build.shrineMode, "applyOrder.mode($name)")
            assertEquals(input, result.build.preShrine, "applyOrder.preShrine($name)")
        }
    }

    @Test
    fun effectiveAttributesAndDerivedStatsMatchGolden() {
        for (c in cases()) {
            val name = c["name"]?.let { (it as? JsonPrimitive)?.content } ?: "?"
            val input = attrsOf(c.obj("input"))
            val mastery = jsonObject(c.obj("mastery") ?: JsonObject(emptyMap()))
            // fixture "effective" = attributes minus the pre-mastery map (mode "")
            val build = Build(attributes = input, preMastery = mastery)

            assertEquals(
                attrsOf(c.obj("effective")),
                ShrineRules.effective(build.attributes, ShrineRules.activeMastery(build)),
                "effective($name)",
            )

            val d = c.obj("derived") ?: error("missing derived for $name")
            assertEquals(d.int("spent") ?: 0, Points.spent(build), "spent($name)")
            assertEquals(d.int("power") ?: 0, Points.power(build), "power($name)")
            assertEquals(d.int("pointsLeft") ?: 0, Points.pointsLeft(build), "pointsLeft($name)")
            assertEquals(d.int("pointsUntilNextPower") ?: 0, Points.toNextPower(build), "toNext($name)")
        }
    }
}